name: "Tesseract OCR"
description: "Exposes Tesseract OCR calls over http as REST."
version: "0.1.0_b2"
slug: "tesseract_rest"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386